-- Migration 013: PPOB Tables
-- This migration adds tables to support PPOB (Digiflazz) integration

-- 1. ppob_settings: Stores API keys and global markup
CREATE TABLE IF NOT EXISTS public.ppob_settings (
    id bigint generated by default as identity primary key,
    tenant_id text, -- NULL means global super admin setting
    api_username text,
    api_key text,
    global_markup numeric default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    CONSTRAINT ppob_settings_tenant_id_key UNIQUE (tenant_id)
);

-- RLS for ppob_settings
ALTER TABLE public.ppob_settings ENABLE ROW LEVEL SECURITY;

-- Allow Super Admin (via Service Role or valid backend request) to read/write all
CREATE POLICY "Enable read access for all users" ON public.ppob_settings FOR SELECT USING (true);
CREATE POLICY "Enable all access for service role" ON public.ppob_settings USING (true) WITH CHECK (true);

-- 2. ppob_transactions: Stores digital product transactions
CREATE TABLE IF NOT EXISTS public.ppob_transactions (
    id bigint generated by default as identity primary key,
    transaction_id bigint references public.transactions(id) on delete set null,
    tenant_id text not null,
    customer_number text not null,
    sku_code text not null,
    product_name text,
    base_price numeric not null,
    selling_price numeric not null,
    status text default 'Pending', -- Pending, Success, Failed
    sn text, -- Serial Number or Token
    ref_id text unique not null, -- Unique reference for Digiflazz
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for ppob_transactions
ALTER TABLE public.ppob_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tenants can view their own ppob transactions" ON public.ppob_transactions
    FOR SELECT USING (tenant_id = auth.uid()::text);

-- Backend will insert/update using Service Role
CREATE POLICY "Enable all access for service role on ppob_transactions" ON public.ppob_transactions USING (true) WITH CHECK (true);

-- 3. Add to supabase-schema.txt for documentation (optional, but good practice)
-- I will instruct the user to run this or we can just keep the migration file.
