-- Migration 014: SaaS Billing, Gating, and Broadcast System

-- 1. Subscription Plans
CREATE TABLE IF NOT EXISTS public.subscription_plans (
    id text primary key, -- e.g., 'free', 'basic', 'pro'
    name text not null,
    price numeric not null default 0,
    billing_cycle text default 'monthly', -- 'monthly', 'yearly', 'lifetime'
    features jsonb default '[]'::jsonb, -- array of allowed feature IDs
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ensure columns exist if table was created previously without them
ALTER TABLE IF EXISTS public.subscription_plans ADD COLUMN IF NOT EXISTS price numeric not null default 0;
ALTER TABLE IF EXISTS public.subscription_plans ADD COLUMN IF NOT EXISTS billing_cycle text default 'monthly';
ALTER TABLE IF EXISTS public.subscription_plans ADD COLUMN IF NOT EXISTS features jsonb default '[]'::jsonb;

-- Seed default plans
INSERT INTO public.subscription_plans (id, name, price, billing_cycle, features) VALUES
('free', 'Free Forever', 0, 'lifetime', '["catalog", "variants", "customers", "discounts"]'::jsonb),
('pro_monthly', 'Pro (Bulanan)', 149000, 'monthly', '["catalog", "variants", "customers", "discounts", "stock", "expenses", "history", "ppob", "reports"]'::jsonb),
('pro_yearly', 'Pro (Tahunan)', 1490000, 'yearly', '["catalog", "variants", "customers", "discounts", "stock", "expenses", "history", "ppob", "reports"]'::jsonb)
ON CONFLICT (id) DO UPDATE SET 
  name = EXCLUDED.name, 
  price = EXCLUDED.price, 
  features = EXCLUDED.features;

-- 2. Tenant Billing (Invoices)
CREATE TABLE IF NOT EXISTS public.tenant_billing (
    id bigint generated by default as identity primary key,
    tenant_id text not null references public.tenants(tenant_id) on delete cascade,
    plan_id text references public.subscription_plans(id),
    amount numeric not null,
    status text default 'pending', -- 'pending', 'paid', 'failed'
    payment_method text,
    xendit_invoice_id text,
    xendit_invoice_url text,
    paid_at timestamp with time zone,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.tenant_billing ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenants can view own billing" ON public.tenant_billing FOR SELECT USING (tenant_id = auth.uid()::text);
CREATE POLICY "Enable all for service role on billing" ON public.tenant_billing USING (true) WITH CHECK (true);

-- 3. Update Tenants Table
ALTER TABLE public.tenants 
ADD COLUMN IF NOT EXISTS plan_id text references public.subscription_plans(id) default 'free',
ADD COLUMN IF NOT EXISTS subscription_status text default 'active', -- 'active', 'past_due'
ADD COLUMN IF NOT EXISTS subscription_end_date timestamp with time zone;

-- 4. Broadcast Messages
CREATE TABLE IF NOT EXISTS public.broadcast_messages (
    id bigint generated by default as identity primary key,
    title text not null,
    message text not null,
    type text default 'info', -- 'info', 'warning', 'promo'
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.broadcast_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can read active broadcasts" ON public.broadcast_messages FOR SELECT USING (is_active = true);
CREATE POLICY "Enable all for service role on broadcasts" ON public.broadcast_messages USING (true) WITH CHECK (true);
