-- Migration 017: PPOB Tenant Balances & E-Wallet
-- Tabel ini menyimpan saldo internal (Deposit) setiap tenant untuk transaksi PPOB

-- 1. Tabel Saldo Tenant
CREATE TABLE IF NOT EXISTS public.tenant_balances (
    tenant_id text primary key references public.tenants(tenant_id) on delete cascade,
    balance numeric not null default 0 CHECK (balance >= 0),
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS untuk tenant_balances
ALTER TABLE public.tenant_balances ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tenants can view own balance" ON public.tenant_balances
    FOR SELECT USING (tenant_id = public.get_auth_tenant_id());

-- Backend Service Role memiliki akses penuh
CREATE POLICY "Service Role can manage balances" ON public.tenant_balances
    USING (true) WITH CHECK (true);

-- Trigger auto-create balance for new tenants (OBSOLETE: Replaced by outlet-based balance in migration 030)
-- This function is kept for reference but the trigger is dropped to avoid ON CONFLICT errors
CREATE OR REPLACE FUNCTION create_tenant_balance()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- No longer used since migration 030
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_create_tenant_balance ON public.tenants;

-- Sisipkan saldo 0 untuk tenant yang sudah ada
INSERT INTO public.tenant_balances (tenant_id, balance)
SELECT tenant_id, 0 FROM public.tenants
ON CONFLICT (tenant_id) DO NOTHING;


-- 2. Tabel Mutasi Saldo (Riwayat Transaksi)
CREATE TABLE IF NOT EXISTS public.balance_mutations (
    id bigint generated by default as identity primary key,
    tenant_id text not null references public.tenants(tenant_id) on delete cascade,
    amount numeric not null, -- Positif = Masuk (Top Up), Negatif = Keluar (Beli PPOB)
    balance_after numeric not null,
    mutation_type text not null, -- 'TOPUP', 'PPOB_PURCHASE', 'REFUND'
    description text,
    ref_id text, -- ID Referensi (e.g. Invoice Xendit, ID Transaksi PPOB)
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS untuk balance_mutations
ALTER TABLE public.balance_mutations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tenants can view own mutations" ON public.balance_mutations
    FOR SELECT USING (tenant_id = public.get_auth_tenant_id());

CREATE POLICY "Service Role can manage mutations" ON public.balance_mutations
    USING (true) WITH CHECK (true);


-- 3. Fungsi RPC untuk potong saldo secara aman (Atomic Transaction)
CREATE OR REPLACE FUNCTION deduct_tenant_balance(
    p_tenant_id text,
    p_amount numeric,
    p_description text,
    p_ref_id text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_current_balance numeric;
BEGIN
    -- Validasi amount harus positif (jumlah yang mau dipotong)
    IF p_amount <= 0 THEN
        RAISE EXCEPTION 'Amount must be positive';
    END IF;

    -- Lock row untuk mencegah race condition
    SELECT balance INTO v_current_balance
    FROM public.tenant_balances
    WHERE tenant_id = p_tenant_id
    FOR UPDATE;

    IF v_current_balance IS NULL THEN
        RAISE EXCEPTION 'Tenant balance not found';
    END IF;

    IF v_current_balance < p_amount THEN
        RETURN FALSE; -- Saldo tidak cukup
    END IF;

    -- Update saldo
    UPDATE public.tenant_balances
    SET balance = balance - p_amount,
        updated_at = now()
    WHERE tenant_id = p_tenant_id;

    -- Catat mutasi
    INSERT INTO public.balance_mutations (tenant_id, amount, balance_after, mutation_type, description, ref_id)
    VALUES (p_tenant_id, -p_amount, v_current_balance - p_amount, 'PPOB_PURCHASE', p_description, p_ref_id);

    RETURN TRUE;
END;
$$;


-- 4. Fungsi RPC untuk Top Up Saldo secara aman
CREATE OR REPLACE FUNCTION add_tenant_balance(
    p_tenant_id text,
    p_amount numeric,
    p_description text,
    p_ref_id text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_current_balance numeric;
BEGIN
    -- Validasi amount harus positif
    IF p_amount <= 0 THEN
        RAISE EXCEPTION 'Amount must be positive';
    END IF;

    -- Lock row
    SELECT balance INTO v_current_balance
    FROM public.tenant_balances
    WHERE tenant_id = p_tenant_id
    FOR UPDATE;

    IF v_current_balance IS NULL THEN
        RAISE EXCEPTION 'Tenant balance not found';
    END IF;

    -- Update saldo
    UPDATE public.tenant_balances
    SET balance = balance + p_amount,
        updated_at = now()
    WHERE tenant_id = p_tenant_id;

    -- Catat mutasi
    INSERT INTO public.balance_mutations (tenant_id, amount, balance_after, mutation_type, description, ref_id)
    VALUES (p_tenant_id, p_amount, v_current_balance + p_amount, 'TOPUP', p_description, p_ref_id);

    RETURN TRUE;
END;
$$;
