-- Migration 027: Manual Deposit Requests

CREATE TABLE IF NOT EXISTS public.manual_deposit_requests (
    id bigint generated by default as identity primary key,
    tenant_id text not null references public.tenants(tenant_id) on delete cascade,
    amount numeric not null CHECK (amount > 0),
    proof_image text not null, -- Base64 string or URL
    status text not null default 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    reviewed_at timestamp with time zone,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
ALTER TABLE public.manual_deposit_requests ENABLE ROW LEVEL SECURITY;

-- Tenants can insert their own requests
CREATE POLICY "Tenants can insert own deposit requests" ON public.manual_deposit_requests
    FOR INSERT WITH CHECK (tenant_id = public.get_auth_tenant_id());

-- Tenants can view their own requests
CREATE POLICY "Tenants can view own deposit requests" ON public.manual_deposit_requests
    FOR SELECT USING (tenant_id = public.get_auth_tenant_id());

-- Service Role full access
CREATE POLICY "Service Role full access on manual_deposit_requests" ON public.manual_deposit_requests
    USING (true) WITH CHECK (true);
