-- Migration 032: AgraPay Withdrawal Requests

CREATE TABLE IF NOT EXISTS public.tenant_withdrawals (
    id bigint generated by default as identity primary key,
    tenant_id text not null references public.tenants(tenant_id) on delete cascade,
    amount numeric not null CHECK (amount > 0),
    bank_name text not null,
    account_number text not null,
    account_name text not null,
    status text not null default 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    reviewed_at timestamp with time zone,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
ALTER TABLE public.tenant_withdrawals ENABLE ROW LEVEL SECURITY;

-- Tenants can insert their own requests
CREATE POLICY "Tenants can insert own withdrawal requests" ON public.tenant_withdrawals
    FOR INSERT WITH CHECK (tenant_id = public.get_auth_tenant_id());

-- Tenants can view their own requests
CREATE POLICY "Tenants can view own withdrawal requests" ON public.tenant_withdrawals
    FOR SELECT USING (tenant_id = public.get_auth_tenant_id());

-- Service Role full access
CREATE POLICY "Service Role full access on tenant_withdrawals" ON public.tenant_withdrawals
    USING (true) WITH CHECK (true);
